package com.ricky.game.dao;

import com.github.pagehelper.Page;
import com.ricky.game.domain.sys.SysRanking;
import com.ricky.game.domain.sys.SysRankingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface SysRankingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int countByExample(SysRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int deleteByExample(SysRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int insert(SysRanking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int insertSelective(SysRanking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    List<SysRanking> selectByExample(SysRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    SysRanking selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRanking record, @Param("example") SysRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRanking record, @Param("example") SysRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRanking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ranking
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRanking record);
    void updateScore(Long userId, Long score);

    Page<SysRanking> findAll();
}