package com.ricky.game.domain.sys;

import com.ricky.game.utils.type.BaseEntity;

/**
 * Database Table Remarks:
 *   用户分数排行表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_ranking
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SysRanking extends BaseEntity {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ranking.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ranking.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户分数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ranking.user_score
     *
     * @mbggenerated
     */
    private Long userScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ranking.user_id
     *
     * @return the value of sys_ranking.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ranking.user_id
     *
     * @param userId the value for sys_ranking.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ranking.user_name
     *
     * @return the value of sys_ranking.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ranking.user_name
     *
     * @param userName the value for sys_ranking.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ranking.user_score
     *
     * @return the value of sys_ranking.user_score
     *
     * @mbggenerated
     */
    public Long getUserScore() {
        return userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ranking.user_score
     *
     * @param userScore the value for sys_ranking.user_score
     *
     * @mbggenerated
     */
    public void setUserScore(Long userScore) {
        this.userScore = userScore;
    }
}